media:
  input: images
  output: /images
  extensions: [jpg, jpeg]
content:
  - name: pages
    label: Pages
    path: pages
    type: collection
    subfolders: false
    view:
      fields: [permalink, name, meta_title, header_text]
      primary: name
      sort: [order, name]
    fields:
      - { name: header_image, type: image, label: Header Image }
      - { name: header_text, type: string, label: Header Text }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: subtitle, type: string, label: Subtitle }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, type: string }
          - { name: order, type: number }
          - { name: url, type: string }
      - { name: layout, type: string }
      - { name: permalink, type: string }
  - name: news
    label: News
    path: news
    type: collection
    subfolders: false
    fields:
      - { name: header_image, type: image, label: Header Image }
      - { name: title, type: string, label: Title }
      - { name: date, label: Date, type: date }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: subtitle, type: string, label: Subtitle }
      - { name: body, label: Body, type: code, options: { language: markdown } }
  - name: products
    label: Products
    path: products
    type: collection
    subfolders: false
    fields:
      - { name: header_image, type: image, label: Header Image }
      - { name: title, type: string, label: Title }
      - { name: date, label: Date, type: date }
      - name: categories
        label: Categories
        type: reference
        options:
          collection: categories
          multiple: true
          search: "title"
          value: "{name}"
          label: "{title}"
      - { name: price, label: Price, type: number, options: { min: 1 } }
      - { name: body, label: Body, type: code, options: { language: markdown } }
      - { name: features, type: string, label: Features, list: true }
      - name: gallery,
        type: image
        label: Gallery
        options: { multiple: true }
      - { name: header_text, type: string, label: Header Text }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: subtitle, type: string, label: Subtitle }
  - name: categories
    label: Categories
    path: categories
    type: collection
    subfolders: false
    fields:
      - { name: title, type: string, label: Title }
      - { name: header_image, type: image, label: Header Image }
      - { name: header_text, type: string, label: Header Text }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: subtitle, type: string, label: Subtitle }
      - { name: body, label: Body, type: code, options: { language: markdown } }
